### ISSUE TITLE
예쁜 리드미 만들어주세요

### ISSUE THREAD

**Issue by codingbowoo** [dbdydgur2244/vim-setting#1]
저도 쓸래요

**Comment by dbdydgur2244** [comment]
앗 ㅋㅋㅋㅋ 조큼만 기다려주세욧...!
수정해야 할 것들이 있어욧!
리드미는 2-3일 내로 올릴게욬ㅋㅋㅋㅋ

**Comment by dbdydgur2244** [comment]
@codingbowoo  리드미 추가하였습니다! mac에서는 테스트를 해보았는데 다른 환경에서는 테스트를 아직 못해봤어요! ㅋㅋㅋ

**Comment by dbdydgur2244** [comment]
@codingbowoo 현재 mac 기준에서는 이렇게 나옵니다.
<img width="1280" alt="2018-01-19 1 33 32" src="https://user-images.githubusercontent.com/17540844/35134976-5f64a614-fd1d-11e7-9ac6-05c005614170.png">
